"""add visibility column to weather_reports table

Revision ID: 5a72a4c9dd4c
Revises: 19eacb3e8b71
Create Date: 2024-10-09 17:39:43.875236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a72a4c9dd4c'
down_revision: Union[str, None] = '19eacb3e8b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_reports', sa.Column('visibility', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_reports', 'visibility')
    # ### end Alembic commands ###
