services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_weather
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: weatherbot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U superuser -d weatherbot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "weather-bot-postgres:/var/lib/postgresql/data"

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: redis_weather
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  app:
    build:
      context: .
    container_name: app_weather
    env_file:
      - .env.prod
    depends_on:
      - postgres-db
      - redis

volumes:
  weather-bot-postgres:
  redis_data: