name: "weather_bot_dev"

services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres_wb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: weatherbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d weatherbot"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "weather-bot-postgres:/var/lib/postgresql/data"

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: redis_wb
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"


volumes:
  weather-bot-postgres:
  redis_data: