"""add weather_condition column to the weather_reports table

Revision ID: b580bc267fb5
Revises: 89bd942a9f24
Create Date: 2024-10-10 12:55:29.130972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b580bc267fb5'
down_revision: Union[str, None] = '89bd942a9f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_reports', sa.Column('weather_condition', sa.String(), server_default='Данные отсутствуют', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_reports', 'weather_condition')
    # ### end Alembic commands ###
